#!/bin/bash


generate_txt_soft(){
    
    local report_dir="$HOME/reports/txt"
    mkdir -p "$report_dir" 2> /dev/null

    local reportName="report_$(whoami)$(date +%Y-%m-%d%H-%M-%S).txt"
    report_path="$report_dir/$reportName"


    {
        echo "--------------------------------------------------"
        echo "            SYSTEM SCAN REPORT                    "
        echo "--------------------------------------------------"
        echo "Date/Time    : $(date)"
        echo "Hostname     : $(hostname)"
        echo "Current User : $USER"
        echo "--------------------------------------------------"
        echo -e "\n=============================="
        echo "      SOFTWARE INFORMATION    "
        echo "=============================="
        echo ""
    } > "$report_path"


    get_detailed_sw_info | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" >> "$report_path"
    
    echo -e "${GREEN}[✔] Report saved to: $report_path${NC}"
}


generate_txt_hard(){
    
    local report_dir="$HOME/reports/txt"
    mkdir -p "$report_dir" 2> /dev/null

    local reportName="report_$(whoami)$(date +%Y-%m-%d%H-%M-%S).txt"
    report_path="$report_dir/$reportName"


    {
        echo "--------------------------------------------------"
        echo "            SYSTEM SCAN REPORT                    "
        echo "--------------------------------------------------"
        echo "Date/Time    : $(date)"
        echo "Hostname     : $(hostname)"
        echo "Current User : $USER"
        echo "--------------------------------------------------"
        echo -e "\n=============================="
        echo "      HARDWARE INFORMATION    "
        echo "=============================="
        echo ""
    } > "$report_path"


    get_hw_info | sed -r "s/\x1B\[(([0-9;][JKmsu])|([0-9][ABCDEFG]))//g" >> "$report_path"
    
    echo -e "${GREEN}[✔] Report saved to: $report_path${NC}"
}



generate_html_soft(){

    local report_dir="$HOME/reports/html"
    mkdir -p "$report_dir" 2>/dev/null

    local reportName="software_$(whoami)$(date +%Y-%m-%d%H-%M-%S).html"
    report_path="$report_dir/$reportName"

    # collect and clean data
    local sw=$(get_detailed_sw_info 2>/dev/null | sed 's/\x1B\[[0-9;]*m//g')
    local net=$(get_netw_info 2>/dev/null | sed 's/\x1B\[[0-9;]*m//g')

    cat > "$report_path" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Software Report - $(hostname)</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            background: #0d1117;
            color: #c9d1d9;
            font-family: 'Courier New', monospace;
            padding: 40px;
        }

        .header {
            border-bottom: 2px solid #30363d;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .header h1 {
            color: #3fb950;
            font-size: 28px;
            margin-bottom: 10px;
        }

        .meta {
            color: #8b949e;
            font-size: 14px;
            line-height: 1.8;
        }

        .meta span {
            color: #58a6ff;
        }

        .section {
            background: #161b22;
            border: 1px solid #30363d;
            border-left: 4px solid #3fb950;
            border-radius: 6px;
            padding: 20px;
            margin-bottom: 20px;
        }

        .section h2 {
            color: #ffa657;
            font-size: 16px;
            margin-bottom: 15px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        pre {
            color: #c9d1d9;
            font-size: 13px;
            line-height: 1.6;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .footer {
            text-align: center;
            color: #8b949e;
            font-size: 12px;
            margin-top: 40px;
            border-top: 1px solid #30363d;
            padding-top: 20px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>&#x1F4BB; Software Audit Report</h1>
        <div class="meta">
            <p>Hostname : <span>$(hostname)</span></p>
            <p>Date     : <span>$(date)</span></p>
            <p>User     : <span>$USER</span></p>
        </div>
    </div>

    <div class="section">
        <h2>Software Details</h2>
        <pre>$sw</pre>
    </div>

    <div class="section">
        <h2>Network Details</h2>
        <pre>$net</pre>
    </div>

    <div class="footer">
        Generated by System Audit Tool
    </div>

</body>
</html>
EOF

    echo -e "${GREEN}[✔] HTML Report saved to: $report_path${NC}"
}




generate_html_hard(){

    local report_dir="$HOME/reports/html"
    mkdir -p "$report_dir" 2>/dev/null

    local reportName="hardware_$(whoami)$(date +%Y-%m-%d%H-%M-%S).html"
    report_path="$report_dir/$reportName"

    # collect and clean data
    local hw=$(get_detailed_hw_info 2>/dev/null | sed 's/\x1B\[[0-9;]*m//g')

    cat > "$report_path" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hardware Report - $(hostname)</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            background: #0d1117;
            color: #c9d1d9;
            font-family: 'Courier New', monospace;
            padding: 40px;
        }

        .header {
            border-bottom: 2px solid #30363d;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .header h1 {
            color: #58a6ff;
            font-size: 28px;
            margin-bottom: 10px;
        }

        .meta {
            color: #8b949e;
            font-size: 14px;
            line-height: 1.8;
        }

        .meta span {
            color: #3fb950;
        }

        .section {
            background: #161b22;
            border: 1px solid #30363d;
            border-left: 4px solid #58a6ff;
            border-radius: 6px;
            padding: 20px;
            margin-bottom: 20px;
        }

        .section h2 {
            color: #ffa657;
            font-size: 16px;
            margin-bottom: 15px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        pre {
            color: #c9d1d9;
            font-size: 13px;
            line-height: 1.6;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .footer {
            text-align: center;
            color: #8b949e;
            font-size: 12px;
            margin-top: 40px;
            border-top: 1px solid #30363d;
            padding-top: 20px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>&#x1F5A5; Hardware Audit Report</h1>
        <div class="meta">
            <p>Hostname : <span>$(hostname)</span></p>
            <p>Date     : <span>$(date)</span></p>
            <p>User     : <span>$USER</span></p>
        </div>
    </div>

    <div class="section">
        <h2>Hardware Details</h2>
        <pre>$hw</pre>
    </div>

    <div class="footer">
        Generated by System Audit Tool
    </div>

</body>
</html>
EOF

    echo -e "${GREEN}[✔] HTML Report saved to: $report_path${NC}"
}


generate_report_menu_h(){

clear

while(true)
do

echo "1)Save locally(txt)"
echo "2)Save locally(html)"
echo "3)Send via email"
echo "4)return"
local choice_G
 read -p "Eneter your choice" choice_G

 case $choice_G in
  
   1)generate_txt_hard
       ;;
   2)generate_html_hard
      ;;
   3)
      generate_txt_hard
      send_email
      ;;
   4) return
      ;;
   *)
     echo -e "${RED}Invalid option! Try again.${NC}"
     sleep 1
    ;;
    esac
done
}




generate_report_menu_s() {

clear

while(true)
do

echo "1)Save locally(txt)"
echo "2)Save locally(html)"
echo "3)Send via email"
echo "4)return"
   local choice_G
 read -p "Eneter your choice" choice_G

 case $choice_G in
  
   1) 
      generate_txt_soft
       ;;
   2)
     generate_html_soft
       ;;    
   3)
      generate_txt_soft
      send_email
      ;;
   4) return
      ;;
   *)
     echo -e "${RED}Invalid option! Try again.${NC}"
     sleep 1
    ;;
    esac
done
}


